version: "3"

services:
  web:
    platform: linux/arm64/v8
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  app:
    platform: linux/amd64
    build: ./php
    image: php:8.1-fpm
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    platform: linux/amd64
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: posse
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    # tmpfs:
    #     - /var/lib/mysql #一時db
    volumes:
        - ./mysql/sql:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=posse_user
      - PMA_PASSWORD=password
    ports:
      - "4040:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions